version: 2

base_job: &job
  docker:
    - image: circleci/ruby:2.5-node
      environment:
        NODE_VERSION: 1.10.6
        YARN_VERSION: 1.17.0
        BUNLDER_VERSION: 2.0.2
        RAILS_ENV: test

jobs:
  build_ruby:
    <<: *job
    steps:
      - checkout

      - run:
          name: Install ruby dependencies
          command: bundle install
  
  build_js:
    <<: *job
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-{{ .Branch }}
            - npm-

      - run:
          name: Install JS dependencies
          command: yarn install

      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_ruby
      - build_js
