version: 2

app_env: &app_env
  environment:
    NODE_VERSION: 1.10.6
    YARN_VERSION: 1.17.0
    BUNDLER_VERSION: 2.0.2
    BUNDLE_PATH: vendor/bundle
    GEM_HOME: .gem
    GEM_PATH: .gem
    RAILS_ENV: test
    DATABASE_URL: 127.0.0.1

base_job: &job
  docker:
    - image: circleci/ruby:2.5-node
      <<: *app_env

jobs:
  # Install ruby dependencies
  build_ruby:
    <<: *job
    steps:
      - checkout

      - run:
          name: Install bundler
          command: gem install bundler -v $BUNDLER_VERSION

      - restore_cache:
          keys:
            - Gemfile-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - Gemfile-{{ .Branch }}
            - Gemfile-

      - run:
          name: Install ruby dependencies
          command: bundle install
      
      - run:
          name: Check rails works
          command: bundle exec rails --version
      
      - save_cache:
          key: Gemfile-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle
            - .gem
  
  # Install JS dependencies
  build_js:
    <<: *job
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-{{ .Branch }}
            - npm-

      - run:
          name: Install JS dependencies
          command: yarn install

      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  
  test_rails:
    docker:
      - image: circleci/ruby:2.5-node
        <<: *app_env
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_DB: rails_db
          POSTGRES_USER: rails_db_user
          POSTGRES_PASSWORD: rails_db_pw

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: Wait for db
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Setup database
          command: bundle exec rails db:create db:schema:load

      - run:
          name: Run rails tests
          command: bundle exec rails test

      # TODO save test artifacts
  
  test_js:
    <<: *job
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: Run JS tests
          # TODO
          command: yarn --version

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_ruby
      - build_js
      - test_js:
          requires:
           - build_js
      - test_rails:
          requires:
           - build_ruby
           - build_js